Feature/how it works
HackMort/strensiq-hcp pull request #40
Opened 2023-04-18 18:44 UTC by Daniel-Gomez-jpg

how it works page created

2023-04-18 20:21 UTC, HackMort requested changes
Overall check spacing and make sure the images are placed correctly on all screen sizes.

2023-04-18 20:21 UTC, HackMort commented on src/styles/style.scss
> +            font-weight: 700;
This value is the same as on "mobile" we don't need to add this or fix the value if needed.

2023-04-18 20:21 UTC, HackMort commented on src/styles/style.scss
> +            font-size: 30px;
Use Rems not PX

2023-04-18 20:21 UTC, HackMort commented on src/styles/style.scss
> +            font-weight: 500;
Same comment as above. If the font-weight has the same value, we don't need to add it again. It seems to me that you are just copying and pasting from the Figma.

2023-04-18 20:21 UTC, HackMort commented on src/styles/style.scss
> +            line-height: 125%;
Rems not %

2023-04-18 20:21 UTC, HackMort commented on src/styles/style.scss
> +            line-height: 125%;
Rems not %

2023-04-18 20:21 UTC, HackMort commented on src/styles/style.scss
> +                    margin-right: 5px;
Rems not PX

2023-04-18 20:21 UTC, HackMort commented on src/styles/style.scss
> +                    margin-top: 3px;
Rems not PX

2023-04-18 20:21 UTC, HackMort commented on src/styles/style.scss
> +        font-size: 18px;
Rems not PX

2023-04-18 20:21 UTC, HackMort commented on src/styles/style.scss
> +            font-size: 18px;
Rems not PX

2023-04-18 20:21 UTC, HackMort commented on src/pages/how-it-works.astro
> +              <li class="hpp__sub-item">Pi then combines with calcium to form hydroxyapatite crystal, the foundation of
This bullets should be circle not green dot, see screenshot:
![image](https://user-images.githubusercontent.com/6466646/232882488-41345300-511d-42dc-a2a5-8285405dcf1a.png)

2023-04-18 20:21 UTC, HackMort commented on src/pages/how-it-works.astro
> +                    <img src="/assets/images/first-hpp.svg" alt="" class="hpp__image">
This image should go full-width on mobile, without any space  around it.
![image](https://user-images.githubusercontent.com/6466646/232883119-ca01eca9-d2cc-42d8-a021-3c91b4b2c26f.png)

2023-04-18 20:21 UTC, HackMort commented on src/pages/how-it-works.astro
> +                      <img src="/assets/images/hpp-second.svg" alt="" class="hpp__image">
Image should be full-width:
![image](https://user-images.githubusercontent.com/6466646/232883230-2b10c4df-2832-494e-91dd-2d56f9221a3d.png)

2023-04-18 20:21 UTC, HackMort commented on src/pages/how-it-works.astro
> +                        <li class="hpp__sub-item">PLP is required for the metabolism of neurotransmitters</li>
Fix bullet:

![image](https://user-images.githubusercontent.com/6466646/232883371-398bf1ac-aa18-469c-870e-6d13a600ac6a.png)

2023-04-18 20:21 UTC, HackMort commented on src/pages/how-it-works.astro
> +                    <h2 class="hpp__sub-title">In patients with hypophosphatasia, a mutation on the ALPL gene causes deficient alkaline phosphatase, resulting in low alkaline phosphatase activity.</h
There's too much space between this elements:

![image](https://user-images.githubusercontent.com/6466646/232885876-5cfa2fe0-57af-49d2-a1b2-0a2284d942e7.png)

2023-04-18 20:21 UTC, HackMort commented on src/pages/how-it-works.astro
> +                <h1 class="without-strensiq__title">Without STRENSIQ</h1>
Change this to an h2, also check the spacing elements are too close to each other.

![image](https://user-images.githubusercontent.com/6466646/232895492-fecc1397-5dd2-45a9-aafa-d5fb9dcaf2d7.png)

2023-04-19 14:07 UTC, HackMort requested changes
Looks a lot better on mobile.
Check out spacing on destkop view, I still see some spacing issues between elements and images. (starting at 1024px)

![image](https://user-images.githubusercontent.com/6466646/233101169-2c8f2bc8-4ca0-476b-9483-22153cbc8362.png)



Also the images are way too big starting at 1400px the space between the 2 columns is not matching. please fix.
![image](https://user-images.githubusercontent.com/6466646/233101056-26f6079a-4ea5-4327-8a20-ec20d4370fbf.png)

2023-04-19 16:08 UTC, HackMort approved these changes

2023-04-19 16:09 UTC, merged

2023-04-19 17:02 UTC, AndersonCastellon commented on src/styles/settings/_variables.scss
> +$color-bright-gray: rgba(226, 231, 234, 0.5);
Duplicated variable
@Daniel-Gomez-jpg 
@HackMort